import { useCallback, useEffect, useRef, useState } from 'react';
import {
  Button,
  Collapse,
  Input,
  InputNumber,
  Row,
  Col,
  Select,
  Space,
  Switch,
  Table,
  Tag,
  Typography,
} from 'antd';
import {
  ReloadOutlined,
  DatabaseOutlined,
  ThunderboltOutlined,
} from '@ant-design/icons';
import type { VectorService } from '../api/vectors';
import { unwrapVectorData } from '../api/vectors';
import { ErrorBanner, type AwsErrorLike } from './ErrorBanner';
import { errorFromCaught } from '../lib/error';
import { formatJson } from '../lib/format';

export interface QueryFormProps {
  bucketName: string;
  indexName: string;
  vectorService: VectorService;
  dimension?: number;
}

const monoFontFamily = "'JetBrains Mono', ui-monospace, monospace";

function parseJsonArray(value: string): number[] | null {
  if (!value.trim()) return null;
  try {
    const parsed = JSON.parse(value);
    if (!Array.isArray(parsed)) return null;
    return parsed;
  } catch {
    return null;
  }
}

function parseJsonObject(value: string): Record<string, unknown> | null {
  if (!value.trim()) return null;
  try {
    const parsed = JSON.parse(value);
    if (
      parsed === null ||
      typeof parsed !== 'object' ||
      Array.isArray(parsed)
    ) {
      return null;
    }
    return parsed as Record<string, unknown>;
  } catch {
    return null;
  }
}

function generateRandomVector(dim: number): string {
  const arr: number[] = [];
  for (let i = 0; i < dim; i++) {
    arr.push(parseFloat((Math.random() * 2 - 1).toFixed(3)));
  }
  return JSON.stringify(arr);
}

interface ExistingVector {
  key: string;
  data: number[];
}

export function QueryForm({
  bucketName,
  indexName,
  vectorService,
  dimension,
}: QueryFormProps) {
  const [queryVector, setQueryVector] = useState('');
  const [topK, setTopK] = useState<number | null>(10);
  const [filter, setFilter] = useState('');
  const [returnMetadata, setReturnMetadata] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<AwsErrorLike | null>(null);
  const [result, setResult] = useState<Awaited<
    ReturnType<VectorService['queryVectors']>
  > | null>(null);

  const [existingVectors, setExistingVectors] = useState<ExistingVector[]>([]);
  const [vectorLoading, setVectorLoading] = useState(false);
  const [vectorListError, setVectorListError] = useState<AwsErrorLike | null>(
    null
  );

  const autoGeneratedRef = useRef(false);

  useEffect(() => {
    autoGeneratedRef.current = false;
    setQueryVector('');
  }, [bucketName, indexName]);

  useEffect(() => {
    if (
      dimension &&
      dimension > 0 &&
      !queryVector.trim() &&
      !autoGeneratedRef.current
    ) {
      autoGeneratedRef.current = true;
      setQueryVector(generateRandomVector(dimension));
    }
  }, [dimension, queryVector]);

  const handleGenerateRandom = useCallback(() => {
    if (!dimension || dimension <= 0) return;
    setQueryVector(generateRandomVector(dimension));
  }, [dimension]);

  const handleLoadExisting = useCallback(async () => {
    setVectorLoading(true);
    setVectorListError(null);
    try {
      const response = await vectorService.listVectors(bucketName, indexName, {
        maxResults: 10,
        returnData: true,
        returnMetadata: true,
      });
      const vectors: ExistingVector[] = (response.vectors ?? [])
        .map((v) => {
          const data = unwrapVectorData(v.data);
          return data ? { key: v.key ?? '', data } : null;
        })
        .filter((v): v is ExistingVector => v !== null);
      setExistingVectors(vectors);
    } catch (err) {
      setVectorListError(errorFromCaught(err));
    } finally {
      setVectorLoading(false);
    }
  }, [bucketName, indexName, vectorService]);

  const handlePickVector = useCallback(
    (key: string) => {
      const vec = existingVectors.find((v) => v.key === key);
      if (vec) {
        setQueryVector(JSON.stringify(vec.data));
      }
    },
    [existingVectors]
  );

  const handleRun = async () => {
    setError(null);
    setResult(null);
    const parsedVector = parseJsonArray(queryVector);
    if (parsedVector === null) {
      setError({
        name: 'Invalid JSON',
        message: 'Query vector must be a valid JSON array of numbers.',
      });
      return;
    }
    const parsedFilter = filter.trim() ? parseJsonObject(filter) : undefined;
    if (filter.trim() && parsedFilter === null) {
      setError({
        name: 'Invalid JSON',
        message: 'Filter must be a valid JSON object.',
      });
      return;
    }

    setLoading(true);
    try {
      const response = await vectorService.queryVectors(bucketName, indexName, {
        queryVector: parsedVector,
        topK: topK ?? 10,
        ...(parsedFilter !== undefined && parsedFilter !== null
          ? { filter: parsedFilter }
          : {}),
        ...(returnMetadata ? { returnMetadata: true } : {}),
      });
      setResult(response);
    } catch (err) {
      setError(errorFromCaught(err));
    } finally {
      setLoading(false);
    }
  };

  const vectors = result?.vectors ?? [];

  const resultColumns = [
    {
      title: '#',
      width: 48,
      render: (_: unknown, __: unknown, index: number) => (
        <span style={{ color: '#94a3b8', fontFamily: monoFontFamily }}>
          {index + 1}
        </span>
      ),
    },
    {
      title: 'Key',
      dataIndex: 'key',
      render: (key: string) => (
        <Typography.Text
          style={{ fontFamily: monoFontFamily, color: '#f0f4f8' }}
        >
          {key ?? '—'}
        </Typography.Text>
      ),
    },
    {
      title: 'Distance',
      dataIndex: 'distance',
      width: 120,
      render: (v: number | undefined) =>
        v !== undefined ? (
          <Tag color="cyan" style={{ fontFamily: monoFontFamily }}>
            {v.toFixed(2)}
          </Tag>
        ) : (
          '—'
        ),
    },
    {
      title: 'Metadata',
      dataIndex: 'metadata',
      render: (v: Record<string, unknown> | undefined) =>
        v !== undefined ? (
          <pre
            style={{
              margin: 0,
              fontFamily: monoFontFamily,
              fontSize: 12,
              lineHeight: 1.55,
              color: '#cbd5e1',
              background: '#0b0f14',
              padding: '4px 8px',
              borderRadius: 6,
              maxWidth: 400,
              overflow: 'auto',
            }}
          >
            {formatJson(JSON.stringify(v)) ?? JSON.stringify(v)}
          </pre>
        ) : (
          <span style={{ color: '#64748b' }}>—</span>
        ),
    },
  ];

  return (
    <Space direction="vertical" size="middle" style={{ width: '100%' }}>
      <Row gutter={24}>
        <Col xs={24} md={12}>
          <div style={{ marginBottom: 8 }}>
            <Typography.Text strong style={{ color: '#cbd5e1', fontSize: 13 }}>
              Query Vector (JSON array of floats)
            </Typography.Text>
          </div>
          <Input.TextArea
            placeholder="Query vector JSON array, e.g. [0.1, 0.2, 0.3]"
            value={queryVector}
            onChange={(e) => setQueryVector(e.target.value)}
            rows={5}
            style={{
              fontFamily: monoFontFamily,
              fontSize: 13,
              background: '#0b0f14',
              border: '1px solid #1e293b',
              color: '#f0f4f8',
            }}
          />
          <Space style={{ marginTop: 8 }} wrap>
            <Button
              size="small"
              icon={<ThunderboltOutlined />}
              onClick={handleGenerateRandom}
              disabled={!dimension || dimension <= 0}
              style={{
                background: '#1e293b',
                border: '1px solid #334155',
                color: '#f0f4f8',
              }}
            >
              Generate random
            </Button>
            <Button
              size="small"
              icon={<DatabaseOutlined />}
              loading={vectorLoading}
              onClick={() => void handleLoadExisting()}
              style={{
                background: '#1e293b',
                border: '1px solid #334155',
                color: '#f0f4f8',
              }}
            >
              Pick existing vector
            </Button>
            {existingVectors.length > 0 && (
              <Select
                placeholder="Choose vector"
                style={{ minWidth: 200 }}
                onChange={handlePickVector}
                options={existingVectors.map((v) => ({
                  value: v.key,
                  label: v.key,
                }))}
              />
            )}
          </Space>
          {vectorListError && (
            <div style={{ marginTop: 8 }}>
              <ErrorBanner
                error={vectorListError}
                onDismiss={() => setVectorListError(null)}
              />
            </div>
          )}
        </Col>
        <Col xs={24} md={12}>
          <Row gutter={16}>
            <Col span={8}>
              <div style={{ marginBottom: 8 }}>
                <Typography.Text
                  strong
                  style={{ color: '#cbd5e1', fontSize: 13 }}
                >
                  TopK
                </Typography.Text>
              </div>
              <InputNumber
                aria-label="TopK"
                min={1}
                max={1000}
                precision={0}
                value={topK}
                onChange={(v) => setTopK(v)}
                style={{
                  width: '100%',
                  background: '#0b0f14',
                  border: '1px solid #1e293b',
                  color: '#f0f4f8',
                }}
              />
            </Col>
            <Col span={16}>
              <div
                style={{
                  display: 'flex',
                  alignItems: 'center',
                  gap: 8,
                  height: 32,
                }}
              >
                <Switch
                  checked={returnMetadata}
                  onChange={(checked) => setReturnMetadata(checked)}
                />
                <Typography.Text style={{ color: '#cbd5e1', fontSize: 13 }}>
                  Return metadata
                </Typography.Text>
              </div>
            </Col>
          </Row>
          <div style={{ marginTop: 12, marginBottom: 8 }}>
            <Typography.Text strong style={{ color: '#cbd5e1', fontSize: 13 }}>
              Filter (optional)
            </Typography.Text>
          </div>
          <Input.TextArea
            placeholder='{"color": "red"}'
            value={filter}
            onChange={(e) => setFilter(e.target.value)}
            rows={3}
            style={{
              fontFamily: monoFontFamily,
              fontSize: 13,
              background: '#0b0f14',
              border: '1px solid #1e293b',
              color: '#f0f4f8',
            }}
          />
        </Col>
      </Row>

      <Button
        type="primary"
        icon={<ReloadOutlined />}
        loading={loading}
        onClick={() => void handleRun()}
        style={{
          width: '100%',
          height: 40,
          fontWeight: 600,
        }}
      >
        Run query
      </Button>

      <ErrorBanner error={error} onDismiss={() => setError(null)} />

      {result && (
        <>
          {vectors.length === 0 ? (
            <div
              style={{
                textAlign: 'center',
                padding: '48px 24px',
                background: '#151e2e',
                border: '1px dashed #334155',
                borderRadius: 12,
              }}
            >
              <Typography.Text style={{ color: '#94a3b8' }}>
                No vectors matched your query. Try adjusting topK or filters.
              </Typography.Text>
            </div>
          ) : (
            <Table
              rowKey={(r) => r.key ?? ''}
              dataSource={vectors}
              pagination={false}
              columns={resultColumns}
              size="small"
              style={{
                background: '#151e2e',
                border: '1px solid #1e293b',
                borderRadius: 12,
              }}
            />
          )}

          <Collapse
            ghost
            items={[
              {
                key: 'raw',
                label: (
                  <Typography.Text style={{ color: '#94a3b8' }}>
                    Raw JSON
                  </Typography.Text>
                ),
                children: (
                  <pre
                    style={{
                      margin: 0,
                      fontFamily: monoFontFamily,
                      fontSize: 13,
                      lineHeight: 1.55,
                      whiteSpace: 'pre-wrap',
                      wordBreak: 'break-word',
                      color: '#cbd5e1',
                      background: '#0b0f14',
                      padding: 16,
                      borderRadius: 8,
                    }}
                  >
                    {formatJson(JSON.stringify(result)) ??
                      JSON.stringify(result)}
                  </pre>
                ),
              },
            ]}
          />
        </>
      )}
    </Space>
  );
}
